temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"),sep = ";",header = TRUE)
unlink(temp)
data$Time<-strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
data_to_use<-data[data$Date>='2007-02-01' & data$Date<='2007-02-02',]
data_to_use$Global_active_power<-as.numeric(as.character(data_to_use$Global_active_power))
png(filename = "plot1.png",width = 480,height = 480)
hist(data_to_use$Global_active_power,col="red",xlab = "Global Active Power(kilowatts)",main="Global Active Power")
dev.off()
